### ISSUE TITLE
NASA requires API key ?

### ISSUE THREAD

**Issue by flofriday** [public-apis/public-apis#1066]
I just looked at the NASA API website and there it asks me to register with an API key.

Maybe I am getting something wrong here, but if not I would love to fix this. I haven't really done much open source work, but I would love to change that.

Here ist the link I tried: https://api.nasa.gov/

**Comment by Ronkiro** [comment]
There are many APIs at NASA. Some asks for API Keys, Some don't.

For each API, there are the parameters, if there is *apikey* parameter, it will ask for it. Some really need it, and some just gives more options to use.

**Comment by yannbertrand** [comment]
Hey @flofriday, thank you for that review 😄

It's quite complicated. Some APIs offer a number of requests for free and then requires an authentication. Currently, we try to display the first accessible option.

As @Ronkiro said, NASA case is even more complicated since they offer a list of APIs with different authentication processes. So, from my POV, we should stick with the first accessible option which is `No` authentication.

There is a real subject on simplifying all that but I'm still not sure on what the best option would be right now...
