### ISSUE TITLE
Add column for open source?

### ISSUE THREAD

**Issue by clmay** [public-apis/public-apis#1470]
Curious if maintainers/community would be open to adding a column to the tables that indicates whether the API itself is open source or proprietary? I'd be happy to begin going through the list and adding the data, I'm not sure what changes to the build scripts would be necessary.

Add'l aside, why is the link to the website in the sidebar's "About" section set to https://ultimatecourses.com if https://api.publicapis.org exists?

**Comment by yannbertrand** [comment]
Some new columns ideas have been asked before, they're referenced under the #1055 issue. We gotta found out if we want them all, maybe add them but hide them (in an html comment) because the list is already hard to read.

I personally don't have access to the repo settings so I can't change anything related to the repo itself (e.g. adding new maintainers). I've contacted the owner but got no answer for a month now. Will let know the community on the #1268 issue if I got access.

Feel free to comment or watch these issues.

**Comment by clmay** [comment]
Ah, wow, I wasn't fully aware of the current situation the project is facing. And I searched, but there was no way I was going to find #1055 with the terms I was using... 😂

I will watch and wait. Thank you for the update and kudos for trying to breathe some life into this project.
