### ISSUE TITLE
Please Read CONTRIBUTING.md before opening a Pull Request.

### ISSUE THREAD

**Issue by pawelborkar** [public-apis/public-apis#1700]
We appreciate your efforts and time for making a contribution into the Public APIs.

Please make sure you read the [Contributing Guide](https://github.com/public-apis/public-apis/blob/master/CONTRIBUTING.md) and follow the Guidelines before making a Pull Request. It will help you to craft a great PR and will also help you to eliminate the extra steps that you might have to do if you do not follow the [Pull Request Guidelines](https://github.com/public-apis/public-apis/blob/master/CONTRIBUTING.md#pull-request-guidelines).

Thank You.

**Comment by jannielove** [comment]
I am kinda new and still learning thank you 🥰

**Comment by Sintay1994** [comment]
http://ethash.poolbinance.com:8888/

**Comment by pawelborkar** [comment]
@Sintay1994 Don't spam the issues and PRs with anykind of cryptocurrency links or similar. Otherwise strong actions will be taken against the author of that comment.

**Comment by Tohgloam** [comment]
ผมทำขึ้นมาจริง และผมได้วางเอาไว้พื้นที่ส่วนตัวผม ถ้ามีบุคคลที่ไม่หวังดีแฮกเข้ามา หรือชอบสอดรู้เรื่องส่วนตัวของคนอื่น (เจตนาผมเพื่อดักปลา ที่พยายามจะคุกคามผมเพียงเท่านั้นครับ) ผมไม่ได้ แชร์ หรือโพสลงในพื้นที่สาธารณะแต่อย่างได๋

การจัดระเบียบต้องจัดให้ดี ตรวจสอบได้ โปร่งใส ครับ
เราจะเดินอยู่หน้าบ้านและเดินไปพร้อมกันครับผม

ส่งจาก iPhone ของฉัน

เมื่อ 19 ก.ค. 2564 เวลา 12:22 เขียนโดย Pawel Borkar ***@***.***>:

﻿

@Sintay1994<https://github.com/Sintay1994> Don't spam the issues and PRs with anykind of cryptocurrency links or similar. Otherwise strong actions will be taken against the author of that comment.

**Comment by cameron187187** [comment]
my bad. i will read

**Comment by ASMCLIMATIZACION** [comment]
[ASM](https://asmclimatizacion.es/reparacion-aire-acondicionado/): great thanks

**Comment by kdunn2856** [comment]
Thank you for your important and appropriate comment. This is NOT a venue for sales prospecting.

**Comment by Cosxxxx** [comment]
[](https://github.com/all-contributors/all-contributors/issues/578)

**Comment by Cosxxxx** [comment]
[![image](https://user-images.githubusercontent.com/91406075/150576291-463bafec-5790-4112-945d-b343b28990c6.jpeg)](https://github.com/all-contributors/all-contributors/issues/578)

**Comment by SamuelGood26** [comment]
Thank You For The Commet There And Have A Great Day!

**Comment by Blaine2369** [comment]
I'm new to this and don't know what I'm doin

**Comment by kimjuhyun25** [comment]
초보입니다.

**Comment by acifahmed706-droid** [comment]
Dis website is all free
