### ISSUE TITLE
How about a Site for this Project ?

### ISSUE THREAD

**Issue by krishna8421** [public-apis/public-apis#1852]
I was thinking that its kind of difficult to find api in a Readme file, How about a website for Public Api Project, with some basic functions like searching etc.

**Comment by krishna8421** [comment]
The front-end work is almost finished.
Only the search function is missing 

See this:
https://public-apis-site.vercel.app/

GitHub: 
https://github.com/krishna8421/public-apis-site

Hope you like it...

**Comment by matheusfelipeog** [comment]
Hi @krishna8421 😄 

A big THANKS for opening this issue and taking the initiative to create a website for public apis, we really appreciate it a lot. ❤️

Indeed, as more API's are added to public-apis the more difficult it becomes to find a specific API within the readme.md file. We've also identified the need to make a website to implement some features that might be helpful in solving this problem and we're working on it.

You can check the solutions found and a broader discussion about it at PR: #1633 

Although this is currently on hold due to some problems we encountered, we will soon get back to work on it and release it as soon as possible.

But we strongly encourage you to continue your project, thus keeping other options for the community.

For example, another visual option that solves the problem discussed here that is somewhat similar to your project is the [Dev Resources](https://devresourc.es/tools-and-utilities/public-apis) project.

**Comment by krishna8421** [comment]
Hey, 

Thanks for your reply, I'll keep working on the project and make it better. I didn't know you guys are also working on a site. You can ping me anytime if you need any help with web dev. I'll be grateful to help.

Cheers,
Krishna

**Comment by Tohgloam** [comment]
ด้วยเกล้าด้วยกระหม่อม ขอเดชะ

กระผมมีชื่อนามว่า นาย อภิศักดิ์ หันจรัส กระผมเกิดในหมู่บ้าน บ้านที่สถานะไม่รำรวย ผมเห็นประเทศเดินถอยหลัง ผมเห็นประเทศแตกแยก ผมเห็นผู้คนไม่ค่อยให้ใจกัน ไม่รักกันครับ จนความลำบากนั้นวิ่งเข้ามาจนผม และครอบครัว ญาติ ผมจึงทนเห็นไม่ไหว ผมอยากอาสาทำงานครับ

*** กระผมอยากแก้ปัณหาการยุแย้ง การก่อให้เกิดความแตกแยก เช่น การสื่อสารครับ (เป็นอันดับแรก)

*** ในตัวกระผมเองโดนกลุ่มแก้งที่ไม่หวังดี กลั่นแกล้ง คุกคาม ไม่เว้นแต่ละวัน โดยใส่ร้ายบ้าง ปล่อยข่าวว่าเสียชีวิตบ้างครับ ปล่อยข่าวให้ญาติทะเลาะกันครับ ผมทำคนเดียวไม่ไหวแน่นอนครับ ผมต้องมีทีม และความร่วมมือจาก อ.ส ปชช ไทย ครับผม ผมอยากทำให้เป็นระบบ และผู้ถือครองเทคโนโลยี (ต้องมีจิตใจเป็นกลาง คิดถึงส่วนรวมได้ก่อนตัวเอง)

*** เป็นปัญหาที่หนักมากครับที่ต้องแก้ไข ชื่อนั้น กลุ่มนั้น (เขาเรียก แก้ง,หลังบ้าน)

*** แต่ผมใช้ชีวิตบนความลำบากอยู่หน้าบ้านตลอด (ผมเป็นหมากในเกมของพวกเขา) ผมไม่อยากให้ใครต้องเจคแบบผมอีกเลยครับ

*** และตามที่ได้รับหมอบหมายด้วยครับ

ส่งจาก iPhone ของฉัน

เมื่อ 19 ก.ค. 2564 เวลา 10:27 เขียนโดย Krishna Kumar ***@***.***>:

﻿

Closed #1852<https://github.com/public-apis/public-apis/issues/1852>.

**Comment by krishna8421** [comment]
@matheusfelipeog

What is that above mail, and it's in which language?

**Comment by matheusfelipeog** [comment]
> What is that above mail, and it's in which language?

This is spam @krishna8421

**Comment by matheusfelipeog** [comment]
Now your project is in the header of public apis @krishna8421 🎉

See: #1985

**Comment by krishna8421** [comment]
Hey @matheusfelipeog

I am glad you liked the site and added it to the header of your repo. Thanks a million and I really appreciate it😊. I will add more stuff and complete the project, I feel bad I left it with some work pending due to my exams, I'll soon start to work on it again.

You can use https://www.public-apis.ml

**Comment by matheusfelipeog** [comment]
> I will add more stuff and complete the project, I feel bad I left it with some work pending due to my exams, I'll soon start to work on it again.

No problem 😆 

> You can use https://www.public-apis.ml

I will update to this link ;)

**Comment by matheusfelipeog** [comment]
Done ;)

**Comment by krishna8421** [comment]
Hey @matheusfelipeog,

I made some changes to the site XD
Check it out https://public-apis-site.vercel.app

If you have any suggestions, I'll be happy to work on them.

**Comment by matheusfelipeog** [comment]
> Hey @matheusfelipeog,
> 
> I made some changes to the site XD
> Check it out https://public-apis-site.vercel.app
> 
> If you have any suggestions, I'll be happy to work on them.

Wow, this is perfect 🎉🚀
