### ISSUE TITLE
A "Favorites" Section

### ISSUE THREAD

**Issue by nathanmargaglio** [public-apis/public-apis#1960]
As someone who just stumbled upon this repo, I think the concept is great, but I find the huge list of APIs to be daunting.  Since I'm not looking for any particular API at this point (i.e., I'm just browsing), I only scrolled down a few sections before giving up on something that caught my eye.

I think if the maintainers kept a brief list of "favorite" APIs that they presented near the top that listed particularly interesting/cool APIs from the list, then more users would be more likely to engage.  Ideally such a list would provide a variety of APIs from various categories, and would include APIs that are eye-catching or easy to appreciate.  It'd be extra engaging if screenshots/examples/etc. were included (even if just for these "favorites").

**Comment by Sanjeetkushwaha11111** [comment]
"I think if the maintainers kept a brief list of "favorite" APIs"--
Everyone is looking for different API, adding favorites section, can cause distractions of the user.

**Comment by pawelborkar** [comment]
Thanks for the suggestion @nathanmargaglio and @Sanjeetkushwaha11111  for pointing out one of its limitations.

I think there's no need for the **Favorites** Section as of now or no need at all in the future as well because it can cause not only a lot of distractions but also a sense of biasness in the user's mind. At **Public APIs** we want every API to treat the same as well as we also want them to be beginner friendly. Making a Favorites section would not do justice to this. Treating some APIs as favorites and the rest as non-favorites is simply being biased to some of the APIs from the lists. Which is against our core principles at Public APIs. 

>Since I'm not looking for any particular API at this point

When you do, you'll find the right API to use in your project. Having a _Favorites_ section is not the solution since it can cause the above problems. And we want to keep the _Public APIs_ Simple, Open, Unbiased and Beginner Friendly for all.

Thanks for your time and efforts.

**Comment by matheusfelipeog** [comment]
> Thanks for the suggestion @nathanmargaglio and @Sanjeetkushwaha11111 for pointing out one of its limitations.
> 
> I think there's no need for the **Favorites** Section as of now or no need at all in the future as well because it can cause not only a lot of distractions but also a sense of biasness in the user's mind. At **Public APIs** we want every API to treat the same as well as we also want them to be beginner friendly. Making a Favorites section would not do justice to this. Treating some APIs as favorites and the rest as non-favorites is simply being biased to some of the APIs from the lists. Which is against our core principles at Public APIs.
> 
> > Since I'm not looking for any particular API at this point
> 
> When you do, you'll find the right API to use in your project. Having a _Favorites_ section is not the solution since it can cause the above problems. And we want to keep the _Public APIs_ Simple, Open, Unbiased and Beginner Friendly for all.
> 
> Thanks for your time and efforts.

I agree with it

**Comment by matheusfelipeog** [comment]
It seems to me that this is already resolved. Thanks guys.

Closing this issue.
