### ISSUE TITLE
Active Contributors

### ISSUE THREAD

**Issue by FayasNoushad** [public-apis/public-apis#2044]
Please add some active contributors for this repository.

**Comment by matheusfelipeog** [comment]
Thanks for opening this issue @FayasNoushad 😄 

I believe there is no need to add new contributors now as the current maintainers are already doing the job very well. The reason for the delay in reviewing some PRs is probably because we are busy with other things and also with an internal problem that we have.

Just see that practically all PRs have already been reviewed and we are waiting for the response from their creators.
