### ISSUE TITLE
Remove Cat-Facts from Animals

### ISSUE THREAD

**Issue by hippyaki** [public-apis/public-apis#2418]
Refer to PR #934 for more details on this.

Abstract: 

The documentation link has been shifted to `/docs` now. Apart from that, the API is not dependable as it crashes and I haven't received any response from the endpoint yet.
The documentation is not clear of the HTTP methods to be used as well.

**Comment by pawelborkar** [comment]
Hey @hippyaki 
Thanks for opening this issue.
Are you talking about the  Cat-Facts from Animals because Anime doesn't has an API with the name you mentioned.
If so then I try to recreate the issue but found it's working well
![Screenshot (96)](https://user-images.githubusercontent.com/36134699/136687025-d2bb9799-e980-4781-acdf-47f1c106bbdf.png)

**Comment by hippyaki** [comment]
@pawelborkar My bad. I have updated the name. Yes, Cat-Facts from Animals.

Now it is working fine. The day I tried, it was responding 503 error. Somebody can change the API doc page tho.
