### ISSUE TITLE
Git.io no longer accepts urls

### ISSUE THREAD

**Issue by makors** [public-apis/public-apis#3348]
Thanks for looking to open an issue for this project.

If you are opening an issue to suggest adding a new entry, please consider opening a pull request instead!

**Comment by Chamepp** [comment]
## Issue Description

The Git.io API, located in the URL shorteners category is no longer available.

## Steps To Reproduce

1. Heading to the URL shorteners category
2. Click on [Git.io](https://api.doge-meme.lol/docs)
3. Checking [Post Explanation](https://github.blog/2011-11-10-git-io-github-url-shortener/)
4. Checking the [Main Source](https://git.io)
5. Using `curl -i https://git.io -F "url=https://github.com/technoweenie"` command in order to test

## Encounter error in response:
<img width="1440" alt="Screen Shot 2022-11-25 at 11 29 15 AM" src="https://user-images.githubusercontent.com/56440241/203931029-b3ed32e7-9523-4f1b-8423-69ff336ec2b3.png">
<img width="682" alt="Screen Shot 2022-11-25 at 11 18 00 AM" src="https://user-images.githubusercontent.com/56440241/203929705-7dfcbdde-8802-481d-b06f-85fd5345c960.png">

## Problem Cause
- Outdated, the URL shortener was deployed on Nov 11, 2011 and is no longer supported by GitHub

## Next Steps To Be Taken
- Removing the git.io from the URL shorteners

**Comment by matheusfelipeog** [comment]
Hi @makors 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
