### ISSUE TITLE
NASA API website

### ISSUE THREAD

**Issue by Fooooooooool** [public-apis/public-apis#3843]
I just looked at the NASA API website and there it asks me to register with an API key.
Maybe I am getting something wrong here, but if not I would love to fix this. I haven't really done much open source work, but I would love to change that.
Here is the link: https://api.nasa.gov/ 
Someone who wants to join and help can click it.

**Comment by virtadpt** [comment]
Signing up for an API key is free.

**Comment by Astoria-Deville** [comment]
There are many APIs at NASA. Some asks for API Keys, Some don't.
For each API, there are the parameters, if there is apikey parameter, it will ask for it. Some really need it, and some just gives more options to use.
It's quite complicated. Some APIs offer a number of requests for free and then requires an authentication. Currently, we try to display the first accessible option.
NASA case is even more complicated since they offer a list of APIs with different authentication processes. So, from my POV, we should stick with the first accessible option which is authentication.

**Comment by Astoria-Deville** [comment]
There are many APIs at NASA. Some asks for API Keys, Some don't.
For each API, there are the parameters, if there is apikey parameter, it will ask for it. Some really need it, and some just gives more options to use.
It's quite complicated. Some APIs offer a number of requests for free and then requires an authentication. Currently, we try to display the first accessible option.
NASA case is even more complicated since they offer a list of APIs with different authentication processes. So, from my POV, we should stick with the first accessible option which is authentication.

**Comment by Fooooooooool** [comment]
Thank u guys！
